// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PriceIncreaseCalculator is an autogenerated mock type for the PriceIncreaseCalculator type
type PriceIncreaseCalculator struct {
	mock.Mock
}

// PriceIncrease provides a mock function with given fields:
func (_m *PriceIncreaseCalculator) PriceIncrease() (float64, error) {
	ret := _m.Called()

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPriceIncreaseCalculator interface {
	mock.TestingT
	Cleanup(func())
}

// NewPriceIncreaseCalculator creates a new instance of PriceIncreaseCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPriceIncreaseCalculator(t mockConstructorTestingTNewPriceIncreaseCalculator) *PriceIncreaseCalculator {
	mock := &PriceIncreaseCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
